
//发现服务actions
export const EXPLORE_FETCHING_LIST = 'EXPLORE_FETCHING_LIST';
export const EXPLORE_RECEIVE_LIST = 'EXPLORE_RECEIVE_LIST';
//发现好友actions
export const FRIEND_FETCHING_LIST = 'FRIEND_FETCHING_LIST';
export const FRIEND_RECEIVE_LIST = 'FRIEND_RECEIVE_LIST';

//个人中心收藏actions
export const ME_BOOK_MARK_FETCHING_LIST = 'ME_BOOK_MARK_FETCHING_LIST';
export const ME_BOOK_MARK_RECEIVE_LIST = 'ME_BOOK_MARK_RECEIVE_LIST';
//个人中心服务actions
export const ME_OFFER_FETCHING_LIST = 'ME_OFFER_FETCHING_LIST';
export const ME_OFFER_RECEIVE_LIST = 'ME_OFFER_RECEIVE_LIST';
//个人中心好友actions
export const ME_FRIEND_FETCHING_LIST = 'ME_FRIEND_FETCHING_LIST';
export const ME_FRIEND_RECEIVE_LIST = 'ME_FRIEND_RECEIVE_LIST'

