// 轮播actions
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST';
export const RECEIVE_BANNER_LIST = 'RECEIVE_BANNER_LIST';

//发现
export const EXPLORE_FETCHING_LIST = 'EXPLORE_FETCHING_LIST';
export const EXPLORE_RECEIVE_LIST = 'EXPLORE_RECEIVE_LIST';

//个人中心收藏actions
export const ME_BOOK_MARK_FETCHING_LIST = 'ME_BOOK_MARK_FETCHING_LIST';
export const ME_BOOK_MARK_RECEIVE_LIST = 'ME_BOOK_MARK_RECEIVE_LIST';
//个人中心服务actions
export const ME_OFFER_FETCHING_LIST = 'ME_OFFER_FETCHING_LIST';
export const ME_OFFER_RECEIVE_LIST = 'ME_OFFER_RECEIVE_LIST';

// 搜索actions
export const FETCH_KEYWORDS_LIST = 'FETCH_KEYWORDS_LIST';
export const RECEIVE_KEYWORDS_LIST = 'RECEIVE_KEYWORDS_LIST';
export const SELECT_KEYWORD = 'SELECT_KEYWORD';
export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export const CACHE_HISTORY = 'CACHE_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const SETUP_SEARCH_TEXT = 'SETUP_SEARCH_TEXT';
export const FETCH_SEARCH_RESULT_LIST = 'FETCH_SEARCH_RESULT_LIST';
export const RECEIVE_SEARCH_RESULT_LIST = 'RECEIVE_SEARCH_RESULT_LIST';
export const CHANGE_SORT_VIEW_STATUS_SEARCH = 'CHANGE_SORT_VIEW_STATUS_SEARCH';
export const SELECT_SORT_TYPE_SEARCH = 'SELECT_SORT_TYPE_SEARCH';
export const FETCH_SORT_TYPES_LIST_SEARCH = 'FETCH_SORT_TYPES_LIST_SEARCH';
export const RECEIVE_SORT_TYPES_LIST_SEARCH = 'RECEIVE_SORT_TYPES_LIST_SEARCH';
export const ORDER_ASC_OR_DESC_SEARCH = 'ORDER_ASC_OR_DESC_SEARCH';
export const CHANGE_HEALTH_LIGHT_SEARCH = 'CHANGE_HEALTH_LIGHT_SEARCH';
export const SELECT_FOOD_TAG = 'SELECT_FOOD_TAG';
